Hulkar
mrrashidov/todos-backend pull request #12
Opened 2022-07-29 10:40 UTC by HUlkar02

2022-07-29 10:49 UTC, mrrashidov requested changes

2022-08-01 12:40 UTC, mrrashidov requested changes

2022-08-01 12:40 UTC, mrrashidov commented on src/color/color.controller.ts
> +  create(@Body() createColorDto: CreateColorDto):Observable<ColorResponse | Object> {
Qanday type dagi object ?

2022-08-01 12:40 UTC, mrrashidov commented on src/color/color.controller.ts
> +  findAll():Observable<ColorResponse[]> {
Qanday Type dagi array ?

2022-08-01 12:40 UTC, mrrashidov commented on src/color/color.controller.ts
> +    return this.colorService.findOne(Number(id));
id numbermi ?

2022-08-01 12:40 UTC, mrrashidov commented on src/color/color.service.ts
> +      map((color:ColorResponse)=>{
```ts
map((color:ColorResponse)=>{
        return color;
      })

2022-08-01 12:40 UTC, mrrashidov commented on src/color/color.service.ts
> +        colors.forEach(function (v) { delete v.id });
```ts
colors.map(color => ({name:color.name))colors.map(color => ({name:color.name))

2022-08-01 12:40 UTC, mrrashidov commented on src/color/color.service.ts
> +      map((color: ColorResponse) => {
```ts
map((color) => color)

2022-08-01 12:40 UTC, mrrashidov commented on src/color/color.service.ts
> +  update(id: number, updateColorDto: UpdateColorDto): Observable<ColorResponse> {
bu color xaqiqatdan xa authUserId edit qila oladimi ?

2022-08-01 12:40 UTC, mrrashidov commented on src/label/label.service.ts
> +    let label: Label;
```ts
  async findLabel(id: number): Promise<Label> {
   return this.labelRepository.findOneBy({ id })
   .then(res:Label => res)
   .catch(err => err)
  }

2022-08-01 12:40 UTC, mrrashidov commented on src/label/label.service.ts
> +    let label: Label;
Boyle daha iyi diye dusunuyorum :)

2022-08-05 04:59 UTC, hulkar02 commented on src/color/color.service.ts
> +      map((color: ColorResponse) => {
```ts
 map((color: ColorResponse) => color)

2022-08-05 06:29 UTC, mrrashidov approved these changes

2022-08-05 10:32 UTC, merged